In [1]:
import math
import numpy as np

## Арифтетические и логические операторы. Переменные

In [2]:
print(2 + 2)
print(2 ** 3)
print(math.sqrt(25))

4
8
5.0


In [3]:
a = 2 * 2
b = a ** 2

In [6]:
a > 2
a != b
a == b

False

In [11]:
c = True

In [8]:
a = 'str'
a

'str'

In [12]:
type(c)

bool

## Списки

In [14]:
arr = list('string')
arr2 = [1, 2, 3, 'aa', True]
arr3 = []

In [16]:
type(arr2)

list

In [24]:
arr4 = list(range(1,5))
print(type(arr4))
len(arr4)

<class 'list'>


4

In [26]:
arr2[0]
arr2[1] = arr2[0] * 4
arr2

[1, 4, 3, 'aa', True]

In [31]:
#arr3.append(55)
arr2

[1, 4, 3, 'aa', True]

In [32]:
arr3.extend(arr2)
arr3

[44, 44, 55, 1, 4, 3, 'aa', True]

In [11]:
len(arr2)

3

## Индексы и срезы

In [66]:
a = [1, 4, 2, 7, 5, 2]

In [34]:
a[1]

4

In [36]:
a[-2]

5

синтаксис срезов - listvar[START:STOP:STEP]

In [40]:
a[0:4]

[1, 4, 2, 7]

In [41]:
a[:]

[1, 4, 2, 7, 5, 2]

In [17]:
a[1:]

[4, 2, 7, 5, 2]

In [18]:
a[:3]

[1, 4, 2]

In [42]:
a[0:6:2]

[1, 2, 5]

In [19]:
a[::2]

[1, 2, 5]

In [20]:
print(a)
a[::-1]

[1, 4, 2, 7, 5, 2]


[2, 5, 7, 2, 4, 1]

In [21]:
a[:-2]

[1, 4, 2, 7]

In [43]:
a[1:3] = [0, 0, 0]
print(a)

[1, 0, 0, 0, 7, 5, 2]


In [44]:
del a[:-3]
print(a)

[7, 5, 2]


In [ ]:
b = [33, 44]

In [67]:
a + 2

TypeError: can only concatenate list (not "int") to list

In [68]:
a > 2

TypeError: '>' not supported between instances of 'list' and 'int'

## Массивы NumPy

In [70]:
a = np.array([20, 30, 40, 50])

In [47]:
type(a)

numpy.ndarray

In [71]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [58]:
a * 5

array([100, 150, 200, 250])

In [63]:
a + b

array([20, 31, 42, 53])

In [64]:
a - b

array([20, 29, 38, 47])

In [65]:
a < 35

array([ True,  True, False, False])

In [73]:
a[ a < 35 ]

array([20, 30])

In [74]:
np.cos(a)

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [75]:
np.sum(a)

140

In [76]:
a.min()

20

In [77]:
a.mean()

35.0

### Многомерные массивы

In [79]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [92]:
a.shape

(2, 3)

In [83]:
a[1,0]

4

In [86]:
a.min(axis=1)  # Наименьшее число в каждом столбце

array([1, 4])

In [91]:
a.sum(axis=0) # сумма по столбцам

array([5, 7, 9])

In [69]:
a.sum(axis=1) # сумма по строкам

array([ 6, 15])

### Срезы в массивах NumPy

In [94]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [95]:
a[3:7]

array([ 27,  64, 125, 216], dtype=int32)

In [96]:
a[3:7] = 88
a

array([  0,   1,   8,  88,  88,  88,  88, 343, 512, 729], dtype=int32)

### Адресация многомерных массиовов NumPy

In [97]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

In [98]:
b.shape

(5, 4)

In [100]:
print( b[2,3] )
print( b[(2,3)] )
print( b[2][3] )

23
23
23


In [103]:
b[:, 2]

array([ 2, 12, 22, 32, 42])

In [104]:
b[1, :]

array([10, 11, 12, 13])

In [105]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [107]:
b[:, -1]

array([ 3, 13, 23, 33, 43])